# Язык java. Travis CI поддерживает другие языки тоже.
language: java
# Режим обычного пользователя для сборки проекта.
sudo: false

# guides.gradle.org/executing-gradle-builds-on-travisci/
install: true
jdk:
  - oraclejdk8
script:
  - ./gradlew build --scan -s